package traductorxmljson;

import java.io.File;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *10/12/18
 * Este form es el encargado de mostrar las estructuras de datos existentes en 
 * la base de datos, así como prestarse para eliminar, modificar o traducir 
 * una estructura seleccionada, o en su defecto, crear y llenar una
 * @author Fermin Mireles
 */
public class Frmexistentes extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    public String ruta = "";
    Conexion mConexion;
    String nombreTabla = "";
    Frmmodificar mModificar;
    
    //M
    /**Metodo empleado para inicializar o crear el formulario
     */
    public Frmexistentes() {        
         mConexion=new Conexion();
         mModificar = new Frmmodificar();
        try {
            mConexion.conectar("localhost", "traducciones", "root", "");
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnTraducir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstructuras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnTraducir.setText("Traducir");
        btnTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraducirActionPerformed(evt);
            }
        });

        tablaEstructuras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEstructuras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstructurasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEstructuras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTraducir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(45, 45, 45)
                        .addComponent(btnModificar)
                        .addGap(39, 39, 39)
                        .addComponent(btnEliminar)
                        .addGap(40, 40, 40)
                        .addComponent(btnTraducir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //M
    /**Metodo empleado para llevar a cabo la traduccion de una estructura 
     * seleccionada dentro de la tabla de datos
     */
    private void btnTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirActionPerformed
        if(!tablaEstructuras.getSelectionModel().isSelectionEmpty()){
        String tabla= "";
        JFileChooser file = new JFileChooser();
        file.setSelectedFile(new File(tabla));
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int r = file.showSaveDialog(this);
        if(r==JFileChooser.CANCEL_OPTION){
            return;   
        }
        File archivo=file.getSelectedFile();
        ruta = archivo.toString();
        } else {
            JOptionPane.showMessageDialog(this, "¡Favor de seleccionar una estructura!");
        }
    }//GEN-LAST:event_btnTraducirActionPerformed

    //M
    /**Metodo empleado para abrir o ejecutar el form de creación, 
     * empleado para dar de alta nuevas estructuras en la BD
     */
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        new Frmcaptura().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    //M
    /**Metodo empleado para ejecutar el form de modificación, 
     * manda la información que contiene una estructura seleccionada para así 
     * cargarla de manera "automatica en el form de modificación
     */
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!tablaEstructuras.getSelectionModel().isSelectionEmpty()){
            try {
                String esqueletoSQL = "select * from " + nombreTabla + ";";
                ResultSet set = mConexion.Consulta(esqueletoSQL);
                ResultSetMetaData metadata = set.getMetaData();
                
                Vector<String> columnNames = new Vector<>();
                int columnCount = metadata.getColumnCount();
                for (int column = 1; column <= columnCount; column++){
                    columnNames.add(metadata.getColumnName(column));
                }
                
                Vector<Vector<Object>> data = new Vector<>();
                while (set.next()){
                    Vector<Object> vector = new Vector<>();
                    for(int columnIndex = 1; columnIndex <= columnCount; columnIndex++){
                        vector.add(set.getObject(columnIndex));
                    }
                    data.add(vector);
                }

                mModificar.txtNombreTabla.setText(nombreTabla);
                mModificar.nombreTabla = nombreTabla;
                DefaultTableModel Modelocampo = new DefaultTableModel(data,columnNames);
                mModificar.tblExistentes.setModel(Modelocampo);
                mModificar.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "¡Favor de seleccionar una estructura!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    //M
    /**Metodo empleado para llevar a cabo la eliminaciónde una estructura existente
     * en la base de datos. Dicha estructura debe ser seleccionada previamente
     * de la tabla
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!tablaEstructuras.getSelectionModel().isSelectionEmpty()){
            try {
                String sql = "drop table " + nombreTabla + ";";
                mConexion.ejecutarInstruccion(sql);
            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "¡Favor de seleccionar una estructura!");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    //M
    /**Metodo empleado para llevar a cabo la seleccion de una estructura para
     * posterormente eliminar, modificar o traducir dicha estructura
     */
    private void tablaEstructurasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstructurasMouseClicked
        int column = 0;
        int selectedRow = tablaEstructuras.getSelectedRow();
        nombreTabla = tablaEstructuras.getModel().getValueAt(selectedRow, column).toString();
    }//GEN-LAST:event_tablaEstructurasMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    //M
    /**Metodo empleado para cargar las estructuras existentes en la BD
     * al momento de que el form se ejecuta o iniciliza
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            String sql = "show tables;";
            ResultSet set = mConexion.Consulta(sql);
            if (set != null){
                Object[] encabezado = {"Estructuras Existentes"};
                tableModel = new DefaultTableModel(null, encabezado);
                while(set.next()){
                    Object[] fila = {set.getString("Tables_in_traducciones")};
                    tableModel.addRow(fila);
                }
                tablaEstructuras.setModel(tableModel);
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */

    //M
    /**Metodo empleado para llevar a cabo la ejecución de este determinado 
     * formulario
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmexistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmexistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmexistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmexistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new Frmexistentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnTraducir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstructuras;
    // End of variables declaration//GEN-END:variables
}
