/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductorxmljson;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *10/12/18
 * Este form es el encargado de mostrar las estructuras de datos existentes en 
 * la base de datos, así como prestarse para eliminar, modificar o traducir 
 * una estructura seleccionada, o en su defecto, crear y llenar una
 * @author Fermin Mireles
 */

public class Frmmodificar extends javax.swing.JFrame {
    public String nombreTabla;
    Conexion mConexion;
    String nCampo;
    String valorCampo;
    int Id;
    
    /**
     * Creates new form Frmmodificar
     */
    public Frmmodificar() {
         mConexion = new Conexion();
         try {
            mConexion.conectar("localhost", "traducciones", "root", "");
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        JTextField nombreTabla = this.txtNombreTabla;
        JTextField nombreCampo = this.txtNombreCampo;
        JTextArea taValorCampo = this.taValorCampo;
        JTable tblExistentes = this.tblExistentes;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombreTabla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnEliminarCampos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taValorCampo = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnCancelarContenido = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblExistentes = new javax.swing.JTable();
        txtTipo = new javax.swing.JTextField();
        btnEliminarDato = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre de la estructura:");

        jLabel2.setText("Nombre del campo:");

        jLabel3.setText("Tipo del campo:");

        btnCrear.setText("Crear Campo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEliminarCampos.setText("Eliminar Campo");
        btnEliminarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCamposActionPerformed(evt);
            }
        });

        jLabel5.setText("Contenido del campo:");

        taValorCampo.setColumns(20);
        taValorCampo.setRows(5);
        jScrollPane1.setViewportView(taValorCampo);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelarContenido.setText("Regresar");
        btnCancelarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarContenidoMouseClicked(evt);
            }
        });
        btnCancelarContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarContenidoActionPerformed(evt);
            }
        });

        tblExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExistentesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblExistentes);

        btnEliminarDato.setText("Eliminar Dato");
        btnEliminarDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(47, 47, 47)
                .addComponent(btnEliminarDato)
                .addGap(32, 32, 32)
                .addComponent(btnCancelarContenido)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnEliminarCampos))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCampos)
                    .addComponent(btnCrear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelarContenido)
                    .addComponent(btnEliminarDato))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            String sql="alter table " + nombreTabla + " add column " + txtNombreCampo.getText() + " " + txtTipo.getText() + ";";
            mConexion.ejecutarInstruccion(sql);
            JOptionPane.showMessageDialog(this, "¡Columna creada!");
        } catch (SQLException ex) {
            Logger.getLogger(Frmmodificar.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblExistentes.getModel();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!tblExistentes.getSelectionModel().isSelectionEmpty()){
            try{
                String nuevoTNombre = txtNombreTabla.getText();
                String nuevoCNombre = txtNombreCampo.getText();
                String nuevoDato = taValorCampo.getText();
            
                if ((!nombreTabla.equals(nuevoTNombre)) && (txtNombreTabla.getText() != null)){
                    String sql="alter table " + nombreTabla + " rename to " 
                        + nuevoTNombre + ";";
                    mConexion.ejecutarInstruccion(sql);
                    JOptionPane.showMessageDialog(this, "¡El nombre de la estructura ah sido actualizado!");
                } else if((!nCampo.equals(nuevoCNombre) && (txtNombreCampo.getText() != null))){
                    String sql="alter table " + nombreTabla + " change " + nCampo 
                        + " " + nuevoCNombre + " " + txtTipo.getText() + ";";
                    mConexion.ejecutarInstruccion(sql);
                    JOptionPane.showMessageDialog(this, "¡El nombre del campo ah sido actualizado!");
                } else if(!valorCampo.equals(nuevoDato) && (taValorCampo.getText() != null)){
                    String sql="update " + nombreTabla + " set " + nCampo + "='" + nuevoDato + "' where id=" + Id + ";";
                    mConexion.ejecutarInstruccion(sql);
                    JOptionPane.showMessageDialog(this, "¡El valor ah sido actualizado!");
                } else {
                    JOptionPane.showMessageDialog(this, "¡No hay cambios a realizar!");
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "¡Favor de seleccionar un dato a modificar!");
        }
        tblExistentes.getModel();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarContenidoMouseClicked
        new Frmexistentes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarContenidoMouseClicked

    private void tblExistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExistentesMouseClicked
        int selectedColumn = tblExistentes.getSelectedColumn();
        int selectedRow = tblExistentes.getSelectedRow();
        
        txtNombreCampo.setText(tblExistentes.getColumnName(selectedColumn).toString());
        nCampo = txtNombreCampo.getText();
        taValorCampo.setText(tblExistentes.getModel().getValueAt(selectedRow, selectedColumn).toString());
        valorCampo = taValorCampo.getText();
        Id = (int) tblExistentes.getModel().getValueAt(selectedRow,0);
    }//GEN-LAST:event_tblExistentesMouseClicked

    private void btnEliminarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCamposActionPerformed
        if(!tblExistentes.getSelectionModel().isSelectionEmpty()){
            try {
                String sql="alter table " + nombreTabla + " drop column " + nCampo + ";";
                mConexion.ejecutarInstruccion(sql);
                JOptionPane.showMessageDialog(this, "¡Columna eliminada!");
            } catch (SQLException ex) {
                Logger.getLogger(Frmmodificar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tblExistentes.getModel();
    }//GEN-LAST:event_btnEliminarCamposActionPerformed

    private void btnEliminarDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDatoActionPerformed
        if(!tblExistentes.getSelectionModel().isSelectionEmpty()){
            try {
                String sql="delete from " + nombreTabla + " where id=" + Id + ";";
                mConexion.ejecutarInstruccion(sql);
                JOptionPane.showMessageDialog(this, "¡Datos eliminados!");
            } catch (SQLException ex) {
                Logger.getLogger(Frmmodificar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tblExistentes.getModel();
    }//GEN-LAST:event_btnEliminarDatoActionPerformed

    private void btnCancelarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarContenidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmmodificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmmodificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarContenido;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminarCampos;
    private javax.swing.JButton btnEliminarDato;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    public javax.swing.JTextArea taValorCampo;
    public javax.swing.JTable tblExistentes;
    public javax.swing.JTextField txtNombreCampo;
    public javax.swing.JTextField txtNombreTabla;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
